version: "3.5"

services:
  laravel-app:
    build:
      context: "."
      args:
        uid: ${UID}
    container_name: subjewebsite
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    networks:
      backend:
        aliases:
          - subjewebsite

# Create a network bridge to server the app
networks:
  backend:
    name: backend-network
